### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jozhalaj** [andersesbensen/rtl-zwave#9]
@andersesbensen 

Hello,

I would like to ask you. There is no license in the code or in the repository, so this code and its parts are free to use yes?

Our research team is working on the detection of threats and anomalies in IoT Networks.  I want to use this code as collector of Z-Wave traffic. I also tried waving_z, EZ-Wave with scapy-radio but this rtl-zwave works best.

Thanks!

**Comment by andersesbensen** [comment]
Hello sorry for the late reply. Yes feel free to use this code. I would appreciate if you mention the origin of the code in any publications you may create.

Best regards 
Anders 

/Anders

**Comment by jozhalaj** [comment]
Ok, as you wish.

Thank You
JH
